; X3-JAM Server Config

[CONFIG]
GamePort 	    = 16010
WebPort 	    = 16000

; To add more channels with specific OJNList
; Add CH[Number] to [CHANNELS] key with arguments [OJNLIST FileName],[Max Room]
[CHANNELS]
CH1	= OJNLIS1.dat,120
CH2	= dpessg.list,120

[ItemList]
Name = itemlist.dat

; Supported database type: SQLite, MySQL, PostgreSQL, and SQLite
[DATABASE]
URL = mysql://root:@localhost:3306/otwotest

; User default configuration
; This only applied to new user's character
; For Characters use format ID_HERE and seperate by coma ','
; For Items use format {ID_HERE,ITEM_COUNT} and seperated by |
[USER]
MCash		= 15000
Gold		= 15000
FCharacters	= 0,0,0,0,0,0,0,0,0,0,0,36,0,0,0,0
MCharacters	= 0,0,0,0,0,0,0,0,0,0,0,35,0,0,0,0
Items		= {156,9999}|{154,9999}|{152,9999}|{150,9999}|{148,9999}|{146,9999}

; Empty token means it the web allow to do such things without any authentication, but it is not recommended for production use.
[API]
RegistrationToken = 1234567890