[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.52.3", features = ["full"] }
async-trait = "0.1.89"
futures = "0.3.32"
sea-orm = { version = "1.1.20", features = ["sqlx-mysql", "runtime-tokio-native-tls", "macros"] }
sea-orm-migration = { version = "1.1.20", features = ["sqlx-mysql", "runtime-tokio-native-tls"] }
encoder = { path = "../encoder" }
getrandom = "0.4.3"
chrono = "0.4.45"
